using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace EVRC
{
    using CockpitMode = CockpitUIMode.CockpitMode;
    using EDControlButton = EDControlBindings.EDControlButton;

    public static class EDControlBindingsMap
    {

        public static Dictionary<EDControlButton, List<CockpitMode>> controlBindingsMap = new Dictionary<EDControlButton, List<CockpitMode>>()
        {
            //Camera
            {EDControlButton.CamPitchUp , new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamPitchDown, new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamYawLeft, new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamYawRight, new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamTranslateForward, new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamTranslateBackward, new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamTranslateLeft, new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamTranslateRight, new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamTranslateUp, new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamTranslateDown, new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamZoomIn, new List<CockpitMode>(){CockpitMode.Map} },
            {EDControlButton.CamZoomOut, new List<CockpitMode>(){CockpitMode.Map} },
                        
            // UI Controls
            {EDControlButton.UI_Up, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },
            {EDControlButton.UI_Down, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },
            {EDControlButton.UI_Left, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },
            {EDControlButton.UI_Right, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },
            {EDControlButton.UI_Select, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },
            {EDControlButton.UI_Back, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },
            {EDControlButton.UI_Toggle, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },
            {EDControlButton.CycleNextPanel, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },
            {EDControlButton.CyclePreviousPanel, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },
            {EDControlButton.CycleNextPage, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },
            {EDControlButton.CyclePreviousPage, new List<CockpitMode>(){CockpitMode.Map, CockpitMode.CockpitPanel, CockpitMode.MenuMode, CockpitMode.StationServices} },

            //Flight Controls
            {EDControlButton.YawLeftButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.YawRightButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.YawToRollButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.RollLeftButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.RollRightButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.PitchUpButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.PitchDownButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.LeftThrustButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.RightThrustButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.UpThrustButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.DownThrustButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.ForwardThrustButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.BackwardThrustButton, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.ForwardKey, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.BackwardKey, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.SetSpeedMinus100, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter, CockpitMode.InSRV }   },
            {EDControlButton.SetSpeedMinus75, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter, CockpitMode.InSRV }   },
            {EDControlButton.SetSpeedMinus50, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter, CockpitMode.InSRV }   },
            {EDControlButton.SetSpeedMinus25, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter, CockpitMode.InSRV }   },
            {EDControlButton.SetSpeedZero, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter, CockpitMode.InSRV }   },
            {EDControlButton.SetSpeed25, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter, CockpitMode.InSRV }   },
            {EDControlButton.SetSpeed50, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter, CockpitMode.InSRV }   },
            {EDControlButton.SetSpeed75, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter, CockpitMode.InSRV }   },
            {EDControlButton.SetSpeed100, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter, CockpitMode.InSRV }   },
                        
            //Cockpit Controls
            {EDControlButton.ToggleCargoScoop, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.UseAlternateFlightValuesToggle, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.ToggleReverseThrottleInput, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.ToggleFlightAssist, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.UseBoostJuice, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.HyperSuperCombination, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.Supercruise, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.Hyperspace, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.DisableRotationCorrectToggle, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.OrbitLinesToggle, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.EjectAllCargo, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.LandingGearToggle, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.MicrophoneMute, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.UseShieldCell, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.FireChaffLauncher, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.NightVisionToggle, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.DeployHardpointToggle, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.ToggleButtonUpInput, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.DeployHeatSink, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.ShipSpotLightToggle, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.RadarIncreaseRange, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.RadarDecreaseRange, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.ChargeECM, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.EngineColourToggle, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.WeaponColourToggle, new List<CockpitMode>(){ CockpitMode.InMainShip }   },

            // Targeting
            {EDControlButton.SelectTarget, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.CycleNextTarget, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.CyclePreviousTarget, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.SelectHighestThreat, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.CycleNextHostileTarget, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.CyclePreviousHostileTarget, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.CycleNextSubsystem, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.CyclePreviousSubsystem, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.SelectTargetsTarget, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },

            // Wingman & Orders
            {EDControlButton.TargetWingman0, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.TargetWingman1, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.TargetWingman2, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.OrderFocusTarget, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.OrderAggressiveBehaviour, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.OrderDefensiveBehaviour, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.OpenOrders, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.OrderRequestDock, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.OrderFollow, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.OrderHoldFire, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.OrderHoldPosition, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.OpenCodexGoToDiscovery, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.WingNavLock, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
                        
            // Combat
            {EDControlButton.TargetNextRouteSystem, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.PrimaryFire, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.SecondaryFire, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.CycleFireGroupNext, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.CycleFireGroupPrevious, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
                        
            // Pip management
            {EDControlButton.IncreaseEnginesPower, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.IncreaseWeaponsPower, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.IncreaseSystemsPower, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.ResetPowerDistribution, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
                        
            // Focus & Panels
            {EDControlButton.UIFocus, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.FocusLeftPanel, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.FocusCommsPanel, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.QuickCommsPanel, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.FocusRadarPanel, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.FocusRightPanel, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.GalaxyMapOpen, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.SystemMapOpen, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.ExplorationFSSEnter, new List<CockpitMode>(){ CockpitMode.InMainShip }   },
            {EDControlButton.FriendsMenu, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            {EDControlButton.Pause, new List<CockpitMode>(){ CockpitMode.InMainShip, CockpitMode.InFighter }   },
            //{EDControlButton.UI_Up, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
            //{EDControlButton.UI_Down, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
            //{EDControlButton.UI_Left, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
            //{EDControlButton.UI_Right, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
            //{EDControlButton.UI_Select, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
            //{EDControlButton.UI_Back, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
            //{EDControlButton.UI_Toggle, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
            //{EDControlButton.CycleNextPanel, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
            //{EDControlButton.CyclePreviousPanel, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
            //{EDControlButton.CycleNextPage, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
            //{EDControlButton.CyclePreviousPage, new List<CockpitMode>(){ CockpitMode.CockpitPanel }   },
             
            // Station Services
            //{EDControlButton.UI_Up, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            //{EDControlButton.UI_Down, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            //{EDControlButton.UI_Left, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            //{EDControlButton.UI_Right, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            //{EDControlButton.UI_Select, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            //{EDControlButton.UI_Back, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            //{EDControlButton.UI_Toggle, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            //{EDControlButton.CycleNextPanel, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            //{EDControlButton.CyclePreviousPanel, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            //{EDControlButton.CycleNextPage, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            //{EDControlButton.CyclePreviousPage, new List<CockpitMode>(){ CockpitMode.StationServices }   },
            
            // SRV     
            {EDControlButton.ToggleDriveAssist, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.SteerLeftButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.SteerRightButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.IncreaseSpeedButtonMax, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.DecreaseSpeedButtonMax, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.RecallDismissShip, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.VerticalThrustersButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.PhotoCameraToggle_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggyRollLeftButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggyRollRightButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggyPitchUpButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggyPitchDownButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggyPrimaryFireButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggySecondaryFireButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.AutoBreakBuggyButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.HeadlightsBuggyButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.ToggleBuggyTurretButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggyTurretYawLeftButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggyTurretYawRightButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggyTurretPitchUpButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggyTurretPitchDownButton, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.BuggyToggleReverseThrottleInput, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.IncreaseEnginesPower_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.IncreaseWeaponsPower_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.IncreaseSystemsPower_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.ResetPowerDistribution_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.ToggleCargoScoop_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.EjectAllCargo_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.UIFocus_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.FocusLeftPanel_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.FocusCommsPanel_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.QuickCommsPanel_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.FocusRadarPanel_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.FocusRightPanel_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.GalaxyMapOpen_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.SystemMapOpen_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.HeadLookToggle_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },
            {EDControlButton.SelectTarget_Buggy, new List<CockpitMode>(){ CockpitMode.InSRV }   },

             //FSSMode
            {EDControlButton.ExplorationFSSShowHelp, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            {EDControlButton.ExplorationFSSDiscoveryScan, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            {EDControlButton.ExplorationFSSCameraPitchDecreaseButton, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            {EDControlButton.ExplorationFSSCameraPitchIncreaseButton, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            {EDControlButton.ExplorationFSSCameraYawDecreaseButton, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            {EDControlButton.ExplorationFSSCameraYawIncreaseButton, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            {EDControlButton.ExplorationFSSMiniZoomIn, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            {EDControlButton.ExplorationFSSMiniZoomOut, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            {EDControlButton.ExplorationFSSTarget, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            {EDControlButton.ExplorationFSSZoomIn, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            {EDControlButton.ExplorationFSSZoomOut, new List<CockpitMode>(){ CockpitMode.FSSMode }   },
            //DSSMode
            {EDControlButton.ExplorationSAAExitThirdPerson, new List<CockpitMode>(){ CockpitMode.DSSMode }   },
            {EDControlButton.ExplorationSAANextGenus, new List<CockpitMode>(){ CockpitMode.DSSMode }   },
            {EDControlButton.ExplorationSAAPreviousGenus, new List<CockpitMode>(){ CockpitMode.DSSMode }   },
            //MenuMode
            //{EDControlButton.UI_Up, new List<CockpitMode>(){ CockpitMode.MenuMode }   },
            //{EDControlButton.UI_Down, new List<CockpitMode>(){ CockpitMode.MenuMode }   },
            //{EDControlButton.UI_Left, new List<CockpitMode>(){ CockpitMode.MenuMode }   },
            //{EDControlButton.UI_Right, new List<CockpitMode>(){ CockpitMode.MenuMode }   },
            //{EDControlButton.UI_Select, new List<CockpitMode>(){ CockpitMode.MenuMode }   },
            //{EDControlButton.UI_Back, new List<CockpitMode>(){ CockpitMode.MenuMode }   },
             //Landing
            {EDControlButton.YawLeftButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.YawRightButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.PitchUpButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.PitchDownButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.RollLeftButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.RollRightButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.LeftThrustButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.RightThrustButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.UpThrustButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.DownThrustButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.ForwardThrustButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },
            {EDControlButton.BackwardThrustButton_Landing, new List<CockpitMode>(){ CockpitMode.Landing }   },

            {EDControlButton.MouseReset, new List<CockpitMode>()},
            {EDControlButton.HMDReset, new List<CockpitMode>()},
            {EDControlButton.ShowPGScoreSummaryInput, new List<CockpitMode>()},
            {EDControlButton.HeadLookToggle, new List<CockpitMode>()},
            {EDControlButton.PlayerHUDModeToggle, new List<CockpitMode>()},
            {EDControlButton.HeadLookReset, new List<CockpitMode>()},
            {EDControlButton.HeadLookPitchUp, new List<CockpitMode>()},
            {EDControlButton.HeadLookPitchDown, new List<CockpitMode>()},
            {EDControlButton.HeadLookYawLeft, new List<CockpitMode>()},
            {EDControlButton.HeadLookYawRight, new List<CockpitMode>()},
            {EDControlButton.CamTranslateZHold, new List<CockpitMode>()},
            {EDControlButton.GalaxyMapHome, new List<CockpitMode>()},
            {EDControlButton.BuggyCycleFireGroupNext, new List<CockpitMode>()},
            {EDControlButton.BuggyCycleFireGroupPrevious, new List<CockpitMode>()},
            {EDControlButton.OpenCodexGoToDiscovery_Buggy, new List<CockpitMode>()},
            {EDControlButton.PlayerHUDModeToggle_Buggy, new List<CockpitMode>()},
            {EDControlButton.MultiCrewToggleMode, new List<CockpitMode>()},
            {EDControlButton.MultiCrewPrimaryFire, new List<CockpitMode>()},
            {EDControlButton.MultiCrewSecondaryFire, new List<CockpitMode>()},
            {EDControlButton.MultiCrewPrimaryUtilityFire, new List<CockpitMode>()},
            {EDControlButton.MultiCrewSecondaryUtilityFire, new List<CockpitMode>()},
            {EDControlButton.MultiCrewThirdPersonYawLeftButton, new List<CockpitMode>()},
            {EDControlButton.MultiCrewThirdPersonYawRightButton, new List<CockpitMode>()},
            {EDControlButton.MultiCrewThirdPersonPitchUpButton, new List<CockpitMode>()},
            {EDControlButton.MultiCrewThirdPersonPitchDownButton, new List<CockpitMode>()},
            {EDControlButton.MultiCrewThirdPersonFovOutButton, new List<CockpitMode>()},
            {EDControlButton.MultiCrewThirdPersonFovInButton, new List<CockpitMode>()},
            {EDControlButton.MultiCrewCockpitUICycleForward, new List<CockpitMode>()},
            {EDControlButton.MultiCrewCockpitUICycleBackward, new List<CockpitMode>()},
            {EDControlButton.PhotoCameraToggle, new List<CockpitMode>()},
            {EDControlButton.VanityCameraScrollLeft, new List<CockpitMode>()},
            {EDControlButton.VanityCameraScrollRight, new List<CockpitMode>()},
            {EDControlButton.ToggleFreeCam, new List<CockpitMode>()},
            {EDControlButton.VanityCameraOne, new List<CockpitMode>()},
            {EDControlButton.VanityCameraTwo, new List<CockpitMode>()},
            {EDControlButton.VanityCameraThree, new List<CockpitMode>()},
            {EDControlButton.VanityCameraFour, new List<CockpitMode>()},
            {EDControlButton.VanityCameraFive, new List<CockpitMode>()},
            {EDControlButton.VanityCameraSix, new List<CockpitMode>()},
            {EDControlButton.VanityCameraSeven, new List<CockpitMode>()},
            {EDControlButton.VanityCameraEight, new List<CockpitMode>()},
            {EDControlButton.VanityCameraNine, new List<CockpitMode>()},
            {EDControlButton.FreeCamToggleHUD, new List<CockpitMode>()},
            {EDControlButton.FreeCamSpeedInc, new List<CockpitMode>()},
            {EDControlButton.FreeCamSpeedDec, new List<CockpitMode>()},
            {EDControlButton.ToggleReverseThrottleInputFreeCam, new List<CockpitMode>()},
            {EDControlButton.MoveFreeCamForward, new List<CockpitMode>()},
            {EDControlButton.MoveFreeCamBackwards, new List<CockpitMode>()},
            {EDControlButton.MoveFreeCamRight, new List<CockpitMode>()},
            {EDControlButton.MoveFreeCamLeft, new List<CockpitMode>()},
            {EDControlButton.MoveFreeCamUp, new List<CockpitMode>()},
            {EDControlButton.MoveFreeCamDown, new List<CockpitMode>()},
            {EDControlButton.PitchCameraUp, new List<CockpitMode>()},
            {EDControlButton.PitchCameraDown, new List<CockpitMode>()},
            {EDControlButton.YawCameraLeft, new List<CockpitMode>()},
            {EDControlButton.YawCameraRight, new List<CockpitMode>()},
            {EDControlButton.RollCameraLeft, new List<CockpitMode>()},
            {EDControlButton.RollCameraRight, new List<CockpitMode>()},
            {EDControlButton.ToggleRotationLock, new List<CockpitMode>()},
            {EDControlButton.FixCameraRelativeToggle, new List<CockpitMode>()},
            {EDControlButton.FixCameraWorldToggle, new List<CockpitMode>()},
            {EDControlButton.QuitCamera, new List<CockpitMode>()},
            {EDControlButton.ToggleAdvanceMode, new List<CockpitMode>()},
            {EDControlButton.FreeCamZoomIn, new List<CockpitMode>()},
            {EDControlButton.FreeCamZoomOut, new List<CockpitMode>()},
            {EDControlButton.FStopDec, new List<CockpitMode>()},
            {EDControlButton.FStopInc, new List<CockpitMode>()},
            {EDControlButton.StoreEnableRotation, new List<CockpitMode>()},
            {EDControlButton.StoreCamZoomIn, new List<CockpitMode>()},
            {EDControlButton.StoreCamZoomOut, new List<CockpitMode>()},
            {EDControlButton.StoreToggle, new List<CockpitMode>()},
            {EDControlButton.CommanderCreator_Undo, new List<CockpitMode>()},
            {EDControlButton.CommanderCreator_Redo, new List<CockpitMode>()},
            {EDControlButton.CommanderCreator_Rotation_MouseToggle, new List<CockpitMode>()},
            {EDControlButton.GalnetAudio_Play_Pause, new List<CockpitMode>()},
            {EDControlButton.GalnetAudio_SkipForward, new List<CockpitMode>()},
            {EDControlButton.GalnetAudio_SkipBackward, new List<CockpitMode>()},
            {EDControlButton.GalnetAudio_ClearQueue, new List<CockpitMode>()},
            {EDControlButton.ExplorationFSSRadioTuningX_Increase, new List<CockpitMode>()},
            {EDControlButton.ExplorationFSSRadioTuningX_Decrease, new List<CockpitMode>()},
            {EDControlButton.ExplorationFSSQuit, new List<CockpitMode>()},
            {EDControlButton.ExplorationSAAChangeScannedAreaViewToggle, new List<CockpitMode>()},
            {EDControlButton.SAAThirdPersonYawLeftButton, new List<CockpitMode>()},
            {EDControlButton.SAAThirdPersonYawRightButton, new List<CockpitMode>()},
            {EDControlButton.SAAThirdPersonPitchUpButton, new List<CockpitMode>()},
            {EDControlButton.SAAThirdPersonPitchDownButton, new List<CockpitMode>()},
            {EDControlButton.SAAThirdPersonFovOutButton, new List<CockpitMode>()},
            {EDControlButton.SAAThirdPersonFovInButton, new List<CockpitMode>()},
            {EDControlButton.TriggerFieldNeutralizer, new List<CockpitMode>()},
            {EDControlButton.VanityCameraTen, new List<CockpitMode>()},
            {EDControlButton.ExplorationSAAShowHelp, new List<CockpitMode>()},


        };
    }
}
