//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_Menu p_Menu;
        
        private static SteamVR_Input_ActionSet_UI p_UI;
        
        private static SteamVR_Input_ActionSet_CockpitControls p_CockpitControls;
        
        private static SteamVR_Input_ActionSet_FSSControls p_FSSControls;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_Menu Menu
        {
            get
            {
                return SteamVR_Actions.p_Menu.GetCopy<SteamVR_Input_ActionSet_Menu>();
            }
        }
        
        public static SteamVR_Input_ActionSet_UI UI
        {
            get
            {
                return SteamVR_Actions.p_UI.GetCopy<SteamVR_Input_ActionSet_UI>();
            }
        }
        
        public static SteamVR_Input_ActionSet_CockpitControls CockpitControls
        {
            get
            {
                return SteamVR_Actions.p_CockpitControls.GetCopy<SteamVR_Input_ActionSet_CockpitControls>();
            }
        }
        
        public static SteamVR_Input_ActionSet_FSSControls FSSControls
        {
            get
            {
                return SteamVR_Actions.p_FSSControls.GetCopy<SteamVR_Input_ActionSet_FSSControls>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_Menu = ((SteamVR_Input_ActionSet_Menu)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Menu>("/actions/Menu")));
            SteamVR_Actions.p_UI = ((SteamVR_Input_ActionSet_UI)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_UI>("/actions/UI")));
            SteamVR_Actions.p_CockpitControls = ((SteamVR_Input_ActionSet_CockpitControls)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_CockpitControls>("/actions/CockpitControls")));
            SteamVR_Actions.p_FSSControls = ((SteamVR_Input_ActionSet_FSSControls)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_FSSControls>("/actions/FSSControls")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.Menu,
                    SteamVR_Actions.UI,
                    SteamVR_Actions.CockpitControls,
                    SteamVR_Actions.FSSControls};
        }
    }
}
