//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_InteractUI;
        
        private static SteamVR_Action_Boolean p_default_GrabToggle;
        
        private static SteamVR_Action_Boolean p_default_GrabHold;
        
        private static SteamVR_Action_Boolean p_default_GrabPinch;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Boolean p_default_ResetSeatedPosition;
        
        private static SteamVR_Action_Boolean p_default_MaybeResetSeatedPosition;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        private static SteamVR_Action_Boolean p_menu_MenuBack;
        
        private static SteamVR_Action_Boolean p_menu_MenuSelect;
        
        private static SteamVR_Action_Boolean p_menu_MenuNavigateUp;
        
        private static SteamVR_Action_Boolean p_menu_MenuNavigateDown;
        
        private static SteamVR_Action_Boolean p_menu_MenuNavigateLeft;
        
        private static SteamVR_Action_Boolean p_menu_MenuNavigateRight;
        
        private static SteamVR_Action_Boolean p_menu_MenuNavigateTrackpadPress;
        
        private static SteamVR_Action_Boolean p_menu_MenuNavigateTrackpadTouch;
        
        private static SteamVR_Action_Vector2 p_menu_MenuNavigateTrackpadPosition;
        
        private static SteamVR_Action_Boolean p_menu_MenuNestedToggle;
        
        private static SteamVR_Action_Vector2 p_menu_MenuNavigateJoystickPosition;
        
        private static SteamVR_Action_Boolean p_uI_UIBack;
        
        private static SteamVR_Action_Boolean p_uI_UISelect;
        
        private static SteamVR_Action_Boolean p_uI_UINavigateUp;
        
        private static SteamVR_Action_Boolean p_uI_UINavigateDown;
        
        private static SteamVR_Action_Boolean p_uI_UINavigateLeft;
        
        private static SteamVR_Action_Boolean p_uI_UINavigateRight;
        
        private static SteamVR_Action_Boolean p_uI_UINavigateTrackpadPress;
        
        private static SteamVR_Action_Boolean p_uI_UINavigateTrackpadTouch;
        
        private static SteamVR_Action_Vector2 p_uI_UINavigateTrackpadPosition;
        
        private static SteamVR_Action_Boolean p_uI_UITabPrevious;
        
        private static SteamVR_Action_Boolean p_uI_UITabNext;
        
        private static SteamVR_Action_Boolean p_uI_UITabTrackpadPress;
        
        private static SteamVR_Action_Boolean p_uI_UITabTrackpadTouch;
        
        private static SteamVR_Action_Vector2 p_uI_UITabTrackpadPosition;
        
        private static SteamVR_Action_Vector2 p_uI_UINavigateJoystickPosition;
        
        private static SteamVR_Action_Vector2 p_uI_UITabJoystickPosition;
        
        private static SteamVR_Action_Boolean p_cockpitControls_ButtonPrimary;
        
        private static SteamVR_Action_Boolean p_cockpitControls_ButtonSecondary;
        
        private static SteamVR_Action_Boolean p_cockpitControls_ButtonAlt;
        
        private static SteamVR_Action_Boolean p_cockpitControls_ButtonPOV1;
        
        private static SteamVR_Action_Boolean p_cockpitControls_POV1TrackpadPress;
        
        private static SteamVR_Action_Boolean p_cockpitControls_POV1TrackpadTouch;
        
        private static SteamVR_Action_Boolean p_cockpitControls_ButtonPOV2;
        
        private static SteamVR_Action_Vector2 p_cockpitControls_POV1TrackpadPosition;
        
        private static SteamVR_Action_Boolean p_cockpitControls_POV2TrackpadPress;
        
        private static SteamVR_Action_Boolean p_cockpitControls_POV2TrackpadTouch;
        
        private static SteamVR_Action_Vector2 p_cockpitControls_POV2TrackpadPosition;
        
        private static SteamVR_Action_Vector2 p_cockpitControls_POV1JoystickPosition;
        
        private static SteamVR_Action_Vector2 p_cockpitControls_POV2JoystickPosition;
        
        public static SteamVR_Action_Boolean default_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_default_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabToggle
        {
            get
            {
                return SteamVR_Actions.p_default_GrabToggle.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabHold
        {
            get
            {
                return SteamVR_Actions.p_default_GrabHold.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_default_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ResetSeatedPosition
        {
            get
            {
                return SteamVR_Actions.p_default_ResetSeatedPosition.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_MaybeResetSeatedPosition
        {
            get
            {
                return SteamVR_Actions.p_default_MaybeResetSeatedPosition.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean menu_MenuBack
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuBack.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean menu_MenuSelect
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuSelect.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean menu_MenuNavigateUp
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuNavigateUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean menu_MenuNavigateDown
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuNavigateDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean menu_MenuNavigateLeft
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuNavigateLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean menu_MenuNavigateRight
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuNavigateRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean menu_MenuNavigateTrackpadPress
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuNavigateTrackpadPress.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean menu_MenuNavigateTrackpadTouch
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuNavigateTrackpadTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 menu_MenuNavigateTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuNavigateTrackpadPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean menu_MenuNestedToggle
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuNestedToggle.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 menu_MenuNavigateJoystickPosition
        {
            get
            {
                return SteamVR_Actions.p_menu_MenuNavigateJoystickPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UIBack
        {
            get
            {
                return SteamVR_Actions.p_uI_UIBack.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UISelect
        {
            get
            {
                return SteamVR_Actions.p_uI_UISelect.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UINavigateUp
        {
            get
            {
                return SteamVR_Actions.p_uI_UINavigateUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UINavigateDown
        {
            get
            {
                return SteamVR_Actions.p_uI_UINavigateDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UINavigateLeft
        {
            get
            {
                return SteamVR_Actions.p_uI_UINavigateLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UINavigateRight
        {
            get
            {
                return SteamVR_Actions.p_uI_UINavigateRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UINavigateTrackpadPress
        {
            get
            {
                return SteamVR_Actions.p_uI_UINavigateTrackpadPress.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UINavigateTrackpadTouch
        {
            get
            {
                return SteamVR_Actions.p_uI_UINavigateTrackpadTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 uI_UINavigateTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.p_uI_UINavigateTrackpadPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UITabPrevious
        {
            get
            {
                return SteamVR_Actions.p_uI_UITabPrevious.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UITabNext
        {
            get
            {
                return SteamVR_Actions.p_uI_UITabNext.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UITabTrackpadPress
        {
            get
            {
                return SteamVR_Actions.p_uI_UITabTrackpadPress.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean uI_UITabTrackpadTouch
        {
            get
            {
                return SteamVR_Actions.p_uI_UITabTrackpadTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 uI_UITabTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.p_uI_UITabTrackpadPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 uI_UINavigateJoystickPosition
        {
            get
            {
                return SteamVR_Actions.p_uI_UINavigateJoystickPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 uI_UITabJoystickPosition
        {
            get
            {
                return SteamVR_Actions.p_uI_UITabJoystickPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean cockpitControls_ButtonPrimary
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_ButtonPrimary.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cockpitControls_ButtonSecondary
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_ButtonSecondary.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cockpitControls_ButtonAlt
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_ButtonAlt.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cockpitControls_ButtonPOV1
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_ButtonPOV1.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cockpitControls_POV1TrackpadPress
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_POV1TrackpadPress.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cockpitControls_POV1TrackpadTouch
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_POV1TrackpadTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cockpitControls_ButtonPOV2
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_ButtonPOV2.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 cockpitControls_POV1TrackpadPosition
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_POV1TrackpadPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean cockpitControls_POV2TrackpadPress
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_POV2TrackpadPress.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean cockpitControls_POV2TrackpadTouch
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_POV2TrackpadTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 cockpitControls_POV2TrackpadPosition
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_POV2TrackpadPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 cockpitControls_POV1JoystickPosition
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_POV1JoystickPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 cockpitControls_POV2JoystickPosition
        {
            get
            {
                return SteamVR_Actions.p_cockpitControls_POV2JoystickPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_GrabToggle,
                    SteamVR_Actions.default_GrabHold,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_ResetSeatedPosition,
                    SteamVR_Actions.default_MaybeResetSeatedPosition,
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.menu_MenuBack,
                    SteamVR_Actions.menu_MenuSelect,
                    SteamVR_Actions.menu_MenuNavigateUp,
                    SteamVR_Actions.menu_MenuNavigateDown,
                    SteamVR_Actions.menu_MenuNavigateLeft,
                    SteamVR_Actions.menu_MenuNavigateRight,
                    SteamVR_Actions.menu_MenuNavigateTrackpadPress,
                    SteamVR_Actions.menu_MenuNavigateTrackpadTouch,
                    SteamVR_Actions.menu_MenuNavigateTrackpadPosition,
                    SteamVR_Actions.menu_MenuNestedToggle,
                    SteamVR_Actions.menu_MenuNavigateJoystickPosition,
                    SteamVR_Actions.uI_UIBack,
                    SteamVR_Actions.uI_UISelect,
                    SteamVR_Actions.uI_UINavigateUp,
                    SteamVR_Actions.uI_UINavigateDown,
                    SteamVR_Actions.uI_UINavigateLeft,
                    SteamVR_Actions.uI_UINavigateRight,
                    SteamVR_Actions.uI_UINavigateTrackpadPress,
                    SteamVR_Actions.uI_UINavigateTrackpadTouch,
                    SteamVR_Actions.uI_UINavigateTrackpadPosition,
                    SteamVR_Actions.uI_UITabPrevious,
                    SteamVR_Actions.uI_UITabNext,
                    SteamVR_Actions.uI_UITabTrackpadPress,
                    SteamVR_Actions.uI_UITabTrackpadTouch,
                    SteamVR_Actions.uI_UITabTrackpadPosition,
                    SteamVR_Actions.uI_UINavigateJoystickPosition,
                    SteamVR_Actions.uI_UITabJoystickPosition,
                    SteamVR_Actions.cockpitControls_ButtonPrimary,
                    SteamVR_Actions.cockpitControls_ButtonSecondary,
                    SteamVR_Actions.cockpitControls_ButtonAlt,
                    SteamVR_Actions.cockpitControls_ButtonPOV1,
                    SteamVR_Actions.cockpitControls_POV1TrackpadPress,
                    SteamVR_Actions.cockpitControls_POV1TrackpadTouch,
                    SteamVR_Actions.cockpitControls_ButtonPOV2,
                    SteamVR_Actions.cockpitControls_POV1TrackpadPosition,
                    SteamVR_Actions.cockpitControls_POV2TrackpadPress,
                    SteamVR_Actions.cockpitControls_POV2TrackpadTouch,
                    SteamVR_Actions.cockpitControls_POV2TrackpadPosition,
                    SteamVR_Actions.cockpitControls_POV1JoystickPosition,
                    SteamVR_Actions.cockpitControls_POV2JoystickPosition};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_GrabToggle,
                    SteamVR_Actions.default_GrabHold,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_ResetSeatedPosition,
                    SteamVR_Actions.default_MaybeResetSeatedPosition,
                    SteamVR_Actions.menu_MenuBack,
                    SteamVR_Actions.menu_MenuSelect,
                    SteamVR_Actions.menu_MenuNavigateUp,
                    SteamVR_Actions.menu_MenuNavigateDown,
                    SteamVR_Actions.menu_MenuNavigateLeft,
                    SteamVR_Actions.menu_MenuNavigateRight,
                    SteamVR_Actions.menu_MenuNavigateTrackpadPress,
                    SteamVR_Actions.menu_MenuNavigateTrackpadTouch,
                    SteamVR_Actions.menu_MenuNavigateTrackpadPosition,
                    SteamVR_Actions.menu_MenuNestedToggle,
                    SteamVR_Actions.menu_MenuNavigateJoystickPosition,
                    SteamVR_Actions.uI_UIBack,
                    SteamVR_Actions.uI_UISelect,
                    SteamVR_Actions.uI_UINavigateUp,
                    SteamVR_Actions.uI_UINavigateDown,
                    SteamVR_Actions.uI_UINavigateLeft,
                    SteamVR_Actions.uI_UINavigateRight,
                    SteamVR_Actions.uI_UINavigateTrackpadPress,
                    SteamVR_Actions.uI_UINavigateTrackpadTouch,
                    SteamVR_Actions.uI_UINavigateTrackpadPosition,
                    SteamVR_Actions.uI_UITabPrevious,
                    SteamVR_Actions.uI_UITabNext,
                    SteamVR_Actions.uI_UITabTrackpadPress,
                    SteamVR_Actions.uI_UITabTrackpadTouch,
                    SteamVR_Actions.uI_UITabTrackpadPosition,
                    SteamVR_Actions.uI_UINavigateJoystickPosition,
                    SteamVR_Actions.uI_UITabJoystickPosition,
                    SteamVR_Actions.cockpitControls_ButtonPrimary,
                    SteamVR_Actions.cockpitControls_ButtonSecondary,
                    SteamVR_Actions.cockpitControls_ButtonAlt,
                    SteamVR_Actions.cockpitControls_ButtonPOV1,
                    SteamVR_Actions.cockpitControls_POV1TrackpadPress,
                    SteamVR_Actions.cockpitControls_POV1TrackpadTouch,
                    SteamVR_Actions.cockpitControls_ButtonPOV2,
                    SteamVR_Actions.cockpitControls_POV1TrackpadPosition,
                    SteamVR_Actions.cockpitControls_POV2TrackpadPress,
                    SteamVR_Actions.cockpitControls_POV2TrackpadTouch,
                    SteamVR_Actions.cockpitControls_POV2TrackpadPosition,
                    SteamVR_Actions.cockpitControls_POV1JoystickPosition,
                    SteamVR_Actions.cockpitControls_POV2JoystickPosition};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_GrabToggle,
                    SteamVR_Actions.default_GrabHold,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_ResetSeatedPosition,
                    SteamVR_Actions.default_MaybeResetSeatedPosition,
                    SteamVR_Actions.menu_MenuBack,
                    SteamVR_Actions.menu_MenuSelect,
                    SteamVR_Actions.menu_MenuNavigateUp,
                    SteamVR_Actions.menu_MenuNavigateDown,
                    SteamVR_Actions.menu_MenuNavigateLeft,
                    SteamVR_Actions.menu_MenuNavigateRight,
                    SteamVR_Actions.menu_MenuNavigateTrackpadPress,
                    SteamVR_Actions.menu_MenuNavigateTrackpadTouch,
                    SteamVR_Actions.menu_MenuNestedToggle,
                    SteamVR_Actions.uI_UIBack,
                    SteamVR_Actions.uI_UISelect,
                    SteamVR_Actions.uI_UINavigateUp,
                    SteamVR_Actions.uI_UINavigateDown,
                    SteamVR_Actions.uI_UINavigateLeft,
                    SteamVR_Actions.uI_UINavigateRight,
                    SteamVR_Actions.uI_UINavigateTrackpadPress,
                    SteamVR_Actions.uI_UINavigateTrackpadTouch,
                    SteamVR_Actions.uI_UITabPrevious,
                    SteamVR_Actions.uI_UITabNext,
                    SteamVR_Actions.uI_UITabTrackpadPress,
                    SteamVR_Actions.uI_UITabTrackpadTouch,
                    SteamVR_Actions.cockpitControls_ButtonPrimary,
                    SteamVR_Actions.cockpitControls_ButtonSecondary,
                    SteamVR_Actions.cockpitControls_ButtonAlt,
                    SteamVR_Actions.cockpitControls_ButtonPOV1,
                    SteamVR_Actions.cockpitControls_POV1TrackpadPress,
                    SteamVR_Actions.cockpitControls_POV1TrackpadTouch,
                    SteamVR_Actions.cockpitControls_ButtonPOV2,
                    SteamVR_Actions.cockpitControls_POV2TrackpadPress,
                    SteamVR_Actions.cockpitControls_POV2TrackpadTouch};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.menu_MenuNavigateTrackpadPosition,
                    SteamVR_Actions.menu_MenuNavigateJoystickPosition,
                    SteamVR_Actions.uI_UINavigateTrackpadPosition,
                    SteamVR_Actions.uI_UITabTrackpadPosition,
                    SteamVR_Actions.uI_UINavigateJoystickPosition,
                    SteamVR_Actions.uI_UITabJoystickPosition,
                    SteamVR_Actions.cockpitControls_POV1TrackpadPosition,
                    SteamVR_Actions.cockpitControls_POV2TrackpadPosition,
                    SteamVR_Actions.cockpitControls_POV1JoystickPosition,
                    SteamVR_Actions.cockpitControls_POV2JoystickPosition};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_GrabToggle,
                    SteamVR_Actions.default_GrabHold,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_ResetSeatedPosition,
                    SteamVR_Actions.default_MaybeResetSeatedPosition,
                    SteamVR_Actions.menu_MenuBack,
                    SteamVR_Actions.menu_MenuSelect,
                    SteamVR_Actions.menu_MenuNavigateUp,
                    SteamVR_Actions.menu_MenuNavigateDown,
                    SteamVR_Actions.menu_MenuNavigateLeft,
                    SteamVR_Actions.menu_MenuNavigateRight,
                    SteamVR_Actions.menu_MenuNavigateTrackpadPress,
                    SteamVR_Actions.menu_MenuNavigateTrackpadTouch,
                    SteamVR_Actions.menu_MenuNavigateTrackpadPosition,
                    SteamVR_Actions.menu_MenuNestedToggle,
                    SteamVR_Actions.menu_MenuNavigateJoystickPosition,
                    SteamVR_Actions.uI_UIBack,
                    SteamVR_Actions.uI_UISelect,
                    SteamVR_Actions.uI_UINavigateUp,
                    SteamVR_Actions.uI_UINavigateDown,
                    SteamVR_Actions.uI_UINavigateLeft,
                    SteamVR_Actions.uI_UINavigateRight,
                    SteamVR_Actions.uI_UINavigateTrackpadPress,
                    SteamVR_Actions.uI_UINavigateTrackpadTouch,
                    SteamVR_Actions.uI_UINavigateTrackpadPosition,
                    SteamVR_Actions.uI_UITabPrevious,
                    SteamVR_Actions.uI_UITabNext,
                    SteamVR_Actions.uI_UITabTrackpadPress,
                    SteamVR_Actions.uI_UITabTrackpadTouch,
                    SteamVR_Actions.uI_UITabTrackpadPosition,
                    SteamVR_Actions.uI_UINavigateJoystickPosition,
                    SteamVR_Actions.uI_UITabJoystickPosition,
                    SteamVR_Actions.cockpitControls_ButtonPrimary,
                    SteamVR_Actions.cockpitControls_ButtonSecondary,
                    SteamVR_Actions.cockpitControls_ButtonAlt,
                    SteamVR_Actions.cockpitControls_ButtonPOV1,
                    SteamVR_Actions.cockpitControls_POV1TrackpadPress,
                    SteamVR_Actions.cockpitControls_POV1TrackpadTouch,
                    SteamVR_Actions.cockpitControls_ButtonPOV2,
                    SteamVR_Actions.cockpitControls_POV1TrackpadPosition,
                    SteamVR_Actions.cockpitControls_POV2TrackpadPress,
                    SteamVR_Actions.cockpitControls_POV2TrackpadTouch,
                    SteamVR_Actions.cockpitControls_POV2TrackpadPosition,
                    SteamVR_Actions.cockpitControls_POV1JoystickPosition,
                    SteamVR_Actions.cockpitControls_POV2JoystickPosition};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/InteractUI")));
            SteamVR_Actions.p_default_GrabToggle = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabToggle")));
            SteamVR_Actions.p_default_GrabHold = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabHold")));
            SteamVR_Actions.p_default_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabPinch")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_ResetSeatedPosition = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/ResetSeatedPosition")));
            SteamVR_Actions.p_default_MaybeResetSeatedPosition = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/MaybeResetSeatedPosition")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
            SteamVR_Actions.p_menu_MenuBack = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Menu/in/MenuBack")));
            SteamVR_Actions.p_menu_MenuSelect = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Menu/in/MenuSelect")));
            SteamVR_Actions.p_menu_MenuNavigateUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Menu/in/MenuNavigateUp")));
            SteamVR_Actions.p_menu_MenuNavigateDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Menu/in/MenuNavigateDown")));
            SteamVR_Actions.p_menu_MenuNavigateLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Menu/in/MenuNavigateLeft")));
            SteamVR_Actions.p_menu_MenuNavigateRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Menu/in/MenuNavigateRight")));
            SteamVR_Actions.p_menu_MenuNavigateTrackpadPress = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Menu/in/MenuNavigateTrackpadPress")));
            SteamVR_Actions.p_menu_MenuNavigateTrackpadTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Menu/in/MenuNavigateTrackpadTouch")));
            SteamVR_Actions.p_menu_MenuNavigateTrackpadPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Menu/in/MenuNavigateTrackpadPosition")));
            SteamVR_Actions.p_menu_MenuNestedToggle = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Menu/in/MenuNestedToggle")));
            SteamVR_Actions.p_menu_MenuNavigateJoystickPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Menu/in/MenuNavigateJoystickPosition")));
            SteamVR_Actions.p_uI_UIBack = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UIBack")));
            SteamVR_Actions.p_uI_UISelect = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UISelect")));
            SteamVR_Actions.p_uI_UINavigateUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UINavigateUp")));
            SteamVR_Actions.p_uI_UINavigateDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UINavigateDown")));
            SteamVR_Actions.p_uI_UINavigateLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UINavigateLeft")));
            SteamVR_Actions.p_uI_UINavigateRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UINavigateRight")));
            SteamVR_Actions.p_uI_UINavigateTrackpadPress = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UINavigateTrackpadPress")));
            SteamVR_Actions.p_uI_UINavigateTrackpadTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UINavigateTrackpadTouch")));
            SteamVR_Actions.p_uI_UINavigateTrackpadPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/UI/in/UINavigateTrackpadPosition")));
            SteamVR_Actions.p_uI_UITabPrevious = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UITabPrevious")));
            SteamVR_Actions.p_uI_UITabNext = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UITabNext")));
            SteamVR_Actions.p_uI_UITabTrackpadPress = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UITabTrackpadPress")));
            SteamVR_Actions.p_uI_UITabTrackpadTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/UI/in/UITabTrackpadTouch")));
            SteamVR_Actions.p_uI_UITabTrackpadPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/UI/in/UITabTrackpadPosition")));
            SteamVR_Actions.p_uI_UINavigateJoystickPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/UI/in/UINavigateJoystickPosition")));
            SteamVR_Actions.p_uI_UITabJoystickPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/UI/in/UITabJoystickPosition")));
            SteamVR_Actions.p_cockpitControls_ButtonPrimary = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/CockpitControls/in/ButtonPrimary")));
            SteamVR_Actions.p_cockpitControls_ButtonSecondary = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/CockpitControls/in/ButtonSecondary")));
            SteamVR_Actions.p_cockpitControls_ButtonAlt = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/CockpitControls/in/ButtonAlt")));
            SteamVR_Actions.p_cockpitControls_ButtonPOV1 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/CockpitControls/in/ButtonPOV1")));
            SteamVR_Actions.p_cockpitControls_POV1TrackpadPress = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/CockpitControls/in/POV1TrackpadPress")));
            SteamVR_Actions.p_cockpitControls_POV1TrackpadTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/CockpitControls/in/POV1TrackpadTouch")));
            SteamVR_Actions.p_cockpitControls_ButtonPOV2 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/CockpitControls/in/ButtonPOV2")));
            SteamVR_Actions.p_cockpitControls_POV1TrackpadPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/CockpitControls/in/POV1TrackpadPosition")));
            SteamVR_Actions.p_cockpitControls_POV2TrackpadPress = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/CockpitControls/in/POV2TrackpadPress")));
            SteamVR_Actions.p_cockpitControls_POV2TrackpadTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/CockpitControls/in/POV2TrackpadTouch")));
            SteamVR_Actions.p_cockpitControls_POV2TrackpadPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/CockpitControls/in/POV2TrackpadPosition")));
            SteamVR_Actions.p_cockpitControls_POV1JoystickPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/CockpitControls/in/POV1JoystickPosition")));
            SteamVR_Actions.p_cockpitControls_POV2JoystickPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/CockpitControls/in/POV2JoystickPosition")));
        }
    }
}
