//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        public static SteamVR_Action_Boolean @__actions_default_in_GrabPinch;
        
        public static SteamVR_Action_Boolean @__actions_default_in_GrabGrip;
        
        public static SteamVR_Action_Pose @__actions_default_in_Pose;
        
        public static SteamVR_Action_Boolean @__actions_default_in_ActivateUI;
        
        public static SteamVR_Action_Boolean @__actions_default_in_SeatedResetButtonPair;
        
        public static SteamVR_Action_Boolean @__actions_default_in_SeatedResetButtonSingle;
        
        public static SteamVR_Action_Boolean @__actions_default_in_BtnTrigger;
        
        public static SteamVR_Action_Boolean @__actions_default_in_BtnSecondary;
        
        public static SteamVR_Action_Boolean @__actions_default_in_BtnAlt;
        
        public static SteamVR_Action_Boolean @__actions_default_in_TrackpadPress;
        
        public static SteamVR_Action_Boolean @__actions_default_in_JoystickPress;
        
        public static SteamVR_Action_Boolean @__actions_default_in_TrackBtnPress;
        
        public static SteamVR_Action_Vibration @__actions_default_out_Haptic;
        
        public static void Dynamic_InitializeActions()
        {
            SteamVR_Input.@__actions_default_in_GrabPinch.Initialize();
            SteamVR_Input.@__actions_default_in_GrabGrip.Initialize();
            SteamVR_Input.@__actions_default_in_Pose.Initialize();
            SteamVR_Input.@__actions_default_in_ActivateUI.Initialize();
            SteamVR_Input.@__actions_default_in_SeatedResetButtonPair.Initialize();
            SteamVR_Input.@__actions_default_in_SeatedResetButtonSingle.Initialize();
            SteamVR_Input.@__actions_default_in_BtnTrigger.Initialize();
            SteamVR_Input.@__actions_default_in_BtnSecondary.Initialize();
            SteamVR_Input.@__actions_default_in_BtnAlt.Initialize();
            SteamVR_Input.@__actions_default_in_TrackpadPress.Initialize();
            SteamVR_Input.@__actions_default_in_JoystickPress.Initialize();
            SteamVR_Input.@__actions_default_in_TrackBtnPress.Initialize();
            SteamVR_Input.@__actions_default_out_Haptic.Initialize();
        }
        
        public static void Dynamic_InitializeInstanceActions()
        {
            Valve.VR.SteamVR_Input.@__actions_default_in_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_GrabPinch")));
            Valve.VR.SteamVR_Input.@__actions_default_in_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_GrabGrip")));
            Valve.VR.SteamVR_Input.@__actions_default_in_Pose = ((SteamVR_Action_Pose)(SteamVR_Input_References.GetAction("__actions_default_in_Pose")));
            Valve.VR.SteamVR_Input.@__actions_default_in_ActivateUI = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_ActivateUI")));
            Valve.VR.SteamVR_Input.@__actions_default_in_SeatedResetButtonPair = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_SeatedResetButtonPair")));
            Valve.VR.SteamVR_Input.@__actions_default_in_SeatedResetButtonSingle = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_SeatedResetButtonSingle")));
            Valve.VR.SteamVR_Input.@__actions_default_in_BtnTrigger = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_BtnTrigger")));
            Valve.VR.SteamVR_Input.@__actions_default_in_BtnSecondary = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_BtnSecondary")));
            Valve.VR.SteamVR_Input.@__actions_default_in_BtnAlt = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_BtnAlt")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TrackpadPress = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_TrackpadPress")));
            Valve.VR.SteamVR_Input.@__actions_default_in_JoystickPress = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_JoystickPress")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TrackBtnPress = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_TrackBtnPress")));
            Valve.VR.SteamVR_Input.@__actions_default_out_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Input_References.GetAction("__actions_default_out_Haptic")));
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.@__actions_default_in_ActivateUI,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SeatedResetButtonPair,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SeatedResetButtonSingle,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnTrigger,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnSecondary,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnAlt,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TrackpadPress,
                    Valve.VR.SteamVR_Input.@__actions_default_in_JoystickPress,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TrackBtnPress,
                    Valve.VR.SteamVR_Input.@__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.SteamVR_Action_In[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.@__actions_default_in_ActivateUI,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SeatedResetButtonPair,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SeatedResetButtonSingle,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnTrigger,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnSecondary,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnAlt,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TrackpadPress,
                    Valve.VR.SteamVR_Input.@__actions_default_in_JoystickPress,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TrackBtnPress};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.SteamVR_Action_Out[] {
                    Valve.VR.SteamVR_Input.@__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    Valve.VR.SteamVR_Input.@__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.@__actions_default_in_ActivateUI,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SeatedResetButtonPair,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SeatedResetButtonSingle,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnTrigger,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnSecondary,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnAlt,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TrackpadPress,
                    Valve.VR.SteamVR_Input.@__actions_default_in_JoystickPress,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TrackBtnPress};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.SteamVR_Action_In[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.@__actions_default_in_ActivateUI,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SeatedResetButtonPair,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SeatedResetButtonSingle,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnTrigger,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnSecondary,
                    Valve.VR.SteamVR_Input.@__actions_default_in_BtnAlt,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TrackpadPress,
                    Valve.VR.SteamVR_Input.@__actions_default_in_JoystickPress,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TrackBtnPress};
        }
    }
}
