//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Pose Pose;
        
        public Valve.VR.SteamVR_Action_Boolean GrabGrip;
        
        public Valve.VR.SteamVR_Action_Boolean GrabPinch;
        
        public Valve.VR.SteamVR_Action_Boolean ActivateUI;
        
        public Valve.VR.SteamVR_Action_Boolean SeatedResetButtonPair;
        
        public Valve.VR.SteamVR_Action_Boolean SeatedResetButtonSingle;
        
        public Valve.VR.SteamVR_Action_Boolean BtnTrigger;
        
        public Valve.VR.SteamVR_Action_Boolean BtnSecondary;
        
        public Valve.VR.SteamVR_Action_Boolean BtnAlt;
        
        public Valve.VR.SteamVR_Action_Boolean TrackpadPress;
        
        public Valve.VR.SteamVR_Action_Boolean JoystickPress;
        
        public Valve.VR.SteamVR_Action_Boolean TrackBtnPress;
    }
}
