//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Menu : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean MenuBack
        {
            get
            {
                return SteamVR_Actions.menu_MenuBack;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuSelect
        {
            get
            {
                return SteamVR_Actions.menu_MenuSelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuNavigateUp
        {
            get
            {
                return SteamVR_Actions.menu_MenuNavigateUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuNavigateDown
        {
            get
            {
                return SteamVR_Actions.menu_MenuNavigateDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuNavigateLeft
        {
            get
            {
                return SteamVR_Actions.menu_MenuNavigateLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuNavigateRight
        {
            get
            {
                return SteamVR_Actions.menu_MenuNavigateRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuNavigateTrackpadPress
        {
            get
            {
                return SteamVR_Actions.menu_MenuNavigateTrackpadPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuNavigateTrackpadTouch
        {
            get
            {
                return SteamVR_Actions.menu_MenuNavigateTrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MenuNavigateTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.menu_MenuNavigateTrackpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuNestedToggle
        {
            get
            {
                return SteamVR_Actions.menu_MenuNestedToggle;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MenuNavigateJoystickPosition
        {
            get
            {
                return SteamVR_Actions.menu_MenuNavigateJoystickPosition;
            }
        }
    }
}
