//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_FSSControls : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ExitFSS
        {
            get
            {
                return SteamVR_Actions.fSSControls_ExitFSS;
            }
        }
        
        public virtual SteamVR_Action_Vector2 CameraControl
        {
            get
            {
                return SteamVR_Actions.fSSControls_CameraControl;
            }
        }
        
        public virtual SteamVR_Action_Boolean CameraControlActivate
        {
            get
            {
                return SteamVR_Actions.fSSControls_CameraControlActivate;
            }
        }
        
        public virtual SteamVR_Action_Boolean TargetCurrentSignal
        {
            get
            {
                return SteamVR_Actions.fSSControls_TargetCurrentSignal;
            }
        }
    }
}
