//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabToggle
        {
            get
            {
                return SteamVR_Actions.default_GrabToggle;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabHold
        {
            get
            {
                return SteamVR_Actions.default_GrabHold;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean ResetSeatedPosition
        {
            get
            {
                return SteamVR_Actions.default_ResetSeatedPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean MaybeResetSeatedPosition
        {
            get
            {
                return SteamVR_Actions.default_MaybeResetSeatedPosition;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RadialSelectorPosition
        {
            get
            {
                return SteamVR_Actions.default_RadialSelectorPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean RadialMenuSelect
        {
            get
            {
                return SteamVR_Actions.default_RadialMenuSelect;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
