//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_FSSControls : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ExitFSS
        {
            get
            {
                return SteamVR_Actions.fSSControls_ExitFSS;
            }
        }
        
        public virtual SteamVR_Action_Vector2 CameraControl
        {
            get
            {
                return SteamVR_Actions.fSSControls_CameraControl;
            }
        }
        
        public virtual SteamVR_Action_Boolean CameraControlActivate
        {
            get
            {
                return SteamVR_Actions.fSSControls_CameraControlActivate;
            }
        }
        
        public virtual SteamVR_Action_Boolean TargetCurrentSignal
        {
            get
            {
                return SteamVR_Actions.fSSControls_TargetCurrentSignal;
            }
        }
        
        public virtual SteamVR_Action_Boolean ZoomIn
        {
            get
            {
                return SteamVR_Actions.fSSControls_ZoomIn;
            }
        }
        
        public virtual SteamVR_Action_Boolean ZoomOut
        {
            get
            {
                return SteamVR_Actions.fSSControls_ZoomOut;
            }
        }
        
        public virtual SteamVR_Action_Boolean SteppedZoomIn
        {
            get
            {
                return SteamVR_Actions.fSSControls_SteppedZoomIn;
            }
        }
        
        public virtual SteamVR_Action_Boolean SteppedZoomOut
        {
            get
            {
                return SteamVR_Actions.fSSControls_SteppedZoomOut;
            }
        }
        
        public virtual SteamVR_Action_Boolean ZoomTrackpadPress
        {
            get
            {
                return SteamVR_Actions.fSSControls_ZoomTrackpadPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean ZoomTrackpadTouch
        {
            get
            {
                return SteamVR_Actions.fSSControls_ZoomTrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ZoomTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.fSSControls_ZoomTrackpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean SteppedZoomTrackpadPress
        {
            get
            {
                return SteamVR_Actions.fSSControls_SteppedZoomTrackpadPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean SteppedZoomTrackpadTouch
        {
            get
            {
                return SteamVR_Actions.fSSControls_SteppedZoomTrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 SteppedZoomTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.fSSControls_SteppedZoomTrackpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean TuneUp
        {
            get
            {
                return SteamVR_Actions.fSSControls_TuneUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean TuneDown
        {
            get
            {
                return SteamVR_Actions.fSSControls_TuneDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean DiscoveryScan
        {
            get
            {
                return SteamVR_Actions.fSSControls_DiscoveryScan;
            }
        }
        
        public virtual SteamVR_Action_Boolean TuneTrackpadPress
        {
            get
            {
                return SteamVR_Actions.fSSControls_TuneTrackpadPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean TuneTrackpadTouch
        {
            get
            {
                return SteamVR_Actions.fSSControls_TuneTrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TuneTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.fSSControls_TuneTrackpadPosition;
            }
        }
    }
}
