//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_CockpitControls : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ButtonPrimary
        {
            get
            {
                return SteamVR_Actions.cockpitControls_ButtonPrimary;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonSecondary
        {
            get
            {
                return SteamVR_Actions.cockpitControls_ButtonSecondary;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonAlt
        {
            get
            {
                return SteamVR_Actions.cockpitControls_ButtonAlt;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonPOV1
        {
            get
            {
                return SteamVR_Actions.cockpitControls_ButtonPOV1;
            }
        }
        
        public virtual SteamVR_Action_Boolean POV1TrackpadPress
        {
            get
            {
                return SteamVR_Actions.cockpitControls_POV1TrackpadPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean POV1TrackpadTouch
        {
            get
            {
                return SteamVR_Actions.cockpitControls_POV1TrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonPOV2
        {
            get
            {
                return SteamVR_Actions.cockpitControls_ButtonPOV2;
            }
        }
        
        public virtual SteamVR_Action_Vector2 POV1TrackpadPosition
        {
            get
            {
                return SteamVR_Actions.cockpitControls_POV1TrackpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean POV2TrackpadPress
        {
            get
            {
                return SteamVR_Actions.cockpitControls_POV2TrackpadPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean POV2TrackpadTouch
        {
            get
            {
                return SteamVR_Actions.cockpitControls_POV2TrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 POV2TrackpadPosition
        {
            get
            {
                return SteamVR_Actions.cockpitControls_POV2TrackpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Vector2 POV1JoystickPosition
        {
            get
            {
                return SteamVR_Actions.cockpitControls_POV1JoystickPosition;
            }
        }
        
        public virtual SteamVR_Action_Vector2 POV2JoystickPosition
        {
            get
            {
                return SteamVR_Actions.cockpitControls_POV2JoystickPosition;
            }
        }
    }
}
