//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_UI : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean UIBack
        {
            get
            {
                return SteamVR_Actions.uI_UIBack;
            }
        }
        
        public virtual SteamVR_Action_Boolean UISelect
        {
            get
            {
                return SteamVR_Actions.uI_UISelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean UINavigateUp
        {
            get
            {
                return SteamVR_Actions.uI_UINavigateUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean UINavigateDown
        {
            get
            {
                return SteamVR_Actions.uI_UINavigateDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean UINavigateLeft
        {
            get
            {
                return SteamVR_Actions.uI_UINavigateLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean UINavigateRight
        {
            get
            {
                return SteamVR_Actions.uI_UINavigateRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean UINavigateTrackpadPress
        {
            get
            {
                return SteamVR_Actions.uI_UINavigateTrackpadPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean UINavigateTrackpadTouch
        {
            get
            {
                return SteamVR_Actions.uI_UINavigateTrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 UINavigateTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.uI_UINavigateTrackpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean UITabPrevious
        {
            get
            {
                return SteamVR_Actions.uI_UITabPrevious;
            }
        }
        
        public virtual SteamVR_Action_Boolean UITabNext
        {
            get
            {
                return SteamVR_Actions.uI_UITabNext;
            }
        }
        
        public virtual SteamVR_Action_Boolean UITabTrackpadPress
        {
            get
            {
                return SteamVR_Actions.uI_UITabTrackpadPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean UITabTrackpadTouch
        {
            get
            {
                return SteamVR_Actions.uI_UITabTrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 UITabTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.uI_UITabTrackpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Vector2 UINavigateJoystickPosition
        {
            get
            {
                return SteamVR_Actions.uI_UINavigateJoystickPosition;
            }
        }
        
        public virtual SteamVR_Action_Vector2 UITabJoystickPosition
        {
            get
            {
                return SteamVR_Actions.uI_UITabJoystickPosition;
            }
        }
    }
}
